name: AI Modules Test

on:
  push:
    paths:
      - 'ai/**'
  pull_request:
    paths:
      - 'ai/**'

jobs:
  ai-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10
      - name: Install AI dependencies
        run: pip install -r ai/requirements.txt
      - name: Run AI Tests
        run: pytest ai/tests/