name: Code Coverage

on:
  push:
    paths:
      - 'backend/**'
      - 'ai/**'
  pull_request:
    paths:
      - 'backend/**'
      - 'ai/**'

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
          pip install -r ai/requirements.txt
          pip install pytest-cov
      - name: Run coverage
        run: |
          pytest --cov=backend --cov=ai --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}