name: Lint & Format Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backend - Python Lint
        uses: psf/black@stable
        with:
          src: "./backend"

      - name: Frontend - ESLint
        run: |
          cd frontend
          npm install
          npm run lint
