name: Lint & Format Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Backend - Python Lint
        if: github.event.pull_request.changed_files.paths.any('backend/**')
        uses: psf/black@stable
        with:
          src: "./backend"

      - name: Frontend - ESLint
        if: github.event.pull_request.changed_files.paths.any('frontend/**')
        run: |
          cd frontend
          npm install
          npm run lint