name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'frontend/**'
      - 'backend/**'
      - 'ai/**'
      - 'tests/**'

jobs:
  pr-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: PR Summary
        run: echo "Pull Request:${{ github.event.pull_request.title }}"

      - name: Enforce Labeling
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            needs-review
            core-feature

      - name: Require 1 approval before merge
        if: ${{ github.event.pull_request.base.ref == 'main' }}
        run: echo "Manual approval required via GitHub UI"
